# Generated by Django 3.2.16 on 2023-03-17 11:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230301_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='prof_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='prof_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
