# Generated by Django 3.2.16 on 2023-03-17 18:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230317_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='prof_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='prof_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
