# Generated by Django 3.2.16 on 2023-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230317_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car_brand',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='car_model',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='car_plate_no',
            field=models.CharField(default='', max_length=11),
        ),
    ]
