# Generated by Django 3.2.16 on 2023-03-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=300)),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('fare', models.CharField(blank=True, max_length=6)),
                ('distance', models.CharField(max_length=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('has_arrived', models.BooleanField(default=False)),
                ('payment_options', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Wallet', 'Wallet'), ('Transfer', 'Transfer')], max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_driver', to='user.driverprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_passenger', to='user.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=300)),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('fare', models.CharField(blank=True, max_length=6)),
                ('distance', models.CharField(max_length=10)),
                ('approx_time', models.CharField(max_length=15)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('has_arrived', models.BooleanField(default=False)),
                ('payment_options', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Wallet', 'Wallet'), ('Transfer', 'Transfer')], max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_driver', to='user.driverprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_passenger', to='user.customerprofile')),
            ],
        ),
    ]
