# Generated by Django 3.2.16 on 2023-03-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedorder',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='proposedorder',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fare',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.DeleteModel(
            name='FinalOrder',
        ),
        migrations.DeleteModel(
            name='ProposedOrder',
        ),
    ]
