# Generated by Django 3.2.16 on 2023-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20230305_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('accepted', 'accepted'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='created', max_length=40, null=True),
        ),
    ]
