# Generated by Django 3.2.16 on 2023-03-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230317_1947'),
        ('trip', '0005_auto_20230328_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('created', 'created'), ('accepted', 'accepted'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='created', max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=300)),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('fare', models.CharField(blank=True, max_length=6)),
                ('distance', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_options', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Wallet', 'Wallet'), ('Transfer', 'Transfer')], max_length=20)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customerprofile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driverprofile')),
            ],
        ),
    ]
