# Generated by Django 3.2.16 on 2023-04-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230317_1947'),
        ('trip', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('created', 'created'), ('accepted', 'accepted'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='created', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengernotif', to='user.customerprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivernotif', to='user.driverprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('created', 'created'), ('accepted', 'accepted'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='created', max_length=40, null=True),
        ),
    ]
